// src/graphql/customSubscriptions.ts
// Custom GraphQL subscriptions that are not auto-generated by Amplify codegen
// This file contains manually-written subscriptions for features like real-time game streaming
//
// Usage:
// import { onGameProcessed } from '../graphql/customSubscriptions';

// ===================================================================
// GAME STREAMING SUBSCRIPTION
// ===================================================================

/**
 * Subscribe to game processing events for a specific batch job
 * 
 * Events are published by the autoScraper Lambda after each game is processed.
 * Use this to display GameListItem components in real-time as games are scraped.
 * 
 * @param jobId - The scraper job ID to subscribe to
 * 
 * @example
 * ```typescript
 * import { generateClient } from 'aws-amplify/api';
 * import { onGameProcessed } from '../graphql/customSubscriptions';
 * 
 * const client = generateClient();
 * const subscription = client.graphql({
 *   query: onGameProcessed,
 *   variables: { jobId: 'abc123' }
 * });
 * 
 * subscription.subscribe({
 *   next: ({ data }) => {
 *     const event = data.onGameProcessed;
 *     console.log(`Game ${event.tournamentId}: ${event.action}`);
 *   },
 *   error: (err) => console.error('Subscription error:', err)
 * });
 * ```
 */
export const onGameProcessed = /* GraphQL */ `
  subscription OnGameProcessed($jobId: ID!) {
    onGameProcessed(jobId: $jobId) {
      jobId
      entityId
      tournamentId
      url
      action
      message
      errorMessage
      processedAt
      durationMs
      dataSource
      s3Key
      gameData {
        name
        gameStatus
        registrationStatus
        gameStartDateTime
        gameEndDateTime
        buyIn
        rake
        guaranteeAmount
        prizepoolPaid
        totalEntries
        totalUniquePlayers
        totalRebuys
        totalAddons
        gameType
        gameVariant
        tournamentType
        gameTags
        venueId
        venueName
        doNotScrape
        existingGameId
      }
      saveResult {
        success
        gameId
        action
        message
      }
    }
  }
`;

// ===================================================================
// TYPE DEFINITIONS
// ===================================================================

/**
 * Variables for onGameProcessed subscription
 */
export interface OnGameProcessedSubscriptionVariables {
  jobId: string;
}

/**
 * Response type for onGameProcessed subscription
 */
export interface OnGameProcessedSubscription {
  onGameProcessed: {
    jobId: string;
    entityId: string;
    tournamentId: number;
    url?: string | null;
    action: 'CREATED' | 'UPDATED' | 'SKIPPED' | 'ERROR' | 'NOT_FOUND' | 'NOT_PUBLISHED';
    message?: string | null;
    errorMessage?: string | null;
    processedAt: string;
    durationMs?: number | null;
    dataSource?: string | null;
    s3Key?: string | null;
    gameData?: {
      name?: string | null;
      gameStatus?: string | null;
      registrationStatus?: string | null;
      gameStartDateTime?: string | null;
      gameEndDateTime?: string | null;
      buyIn?: number | null;
      rake?: number | null;
      guaranteeAmount?: number | null;
      prizepoolPaid?: number | null;
      totalEntries?: number | null;
      totalUniquePlayers?: number | null;
      totalRebuys?: number | null;
      totalAddons?: number | null;
      gameType?: string | null;
      gameVariant?: string | null;
      tournamentType?: string | null;
      gameTags?: string[] | null;
      venueId?: string | null;
      venueName?: string | null;
      doNotScrape?: boolean | null;
      existingGameId?: string | null;
    } | null;
    saveResult?: {
      success: boolean;
      gameId?: string | null;
      action?: string | null;
      message?: string | null;
    } | null;
  } | null;
}

// ===================================================================
// SUBSCRIPTION HELPER
// ===================================================================

/**
 * Helper to create a typed subscription
 * This provides better type inference when using the subscription
 */
export const createGameProcessedSubscription = (jobId: string) => ({
  query: onGameProcessed,
  variables: { jobId } as OnGameProcessedSubscriptionVariables,
});
