// src/graphql/customSubscriptions.ts
// Custom GraphQL subscriptions that are not auto-generated by Amplify codegen
// This file contains manually-written subscriptions for features like real-time game streaming
//
// UPDATED v2.1: FIXED - Added notFoundCount and notPublishedCount to OnJobProgressSubscription
//               interface. These fields were present in the GraphQL query but missing from
//               the TypeScript interface, causing type errors and values not being extracted.
//
// v2.0: Added onJobProgress subscription for real-time job monitoring
//
// Usage:
// import { onGameProcessed, onJobProgress } from '../graphql/customSubscriptions';

// ===================================================================
// GAME STREAMING SUBSCRIPTION
// ===================================================================

/**
 * Subscribe to game processing events for a specific batch job
 * 
 * Events are published by the autoScraper Lambda after each game is processed.
 * Use this to display GameListItem components in real-time as games are scraped.
 * 
 * @param jobId - The scraper job ID to subscribe to
 * 
 * @example
 * ```typescript
 * import { generateClient } from 'aws-amplify/api';
 * import { onGameProcessed } from '../graphql/customSubscriptions';
 * 
 * const client = generateClient();
 * const subscription = client.graphql({
 *   query: onGameProcessed,
 *   variables: { jobId: 'abc123' }
 * });
 * 
 * subscription.subscribe({
 *   next: ({ data }) => {
 *     const event = data.onGameProcessed;
 *     console.log(`Game ${event.tournamentId}: ${event.action}`);
 *   },
 *   error: (err) => console.error('Subscription error:', err)
 * });
 * ```
 */
export const onGameProcessed = /* GraphQL */ `
  subscription OnGameProcessed($jobId: ID!) {
    onGameProcessed(jobId: $jobId) {
      jobId
      entityId
      tournamentId
      url
      action
      message
      errorMessage
      processedAt
      durationMs
      dataSource
      s3Key
      gameData {
        name
        gameStatus
        registrationStatus
        gameStartDateTime
        gameEndDateTime
        buyIn
        rake
        guaranteeAmount
        prizepoolPaid
        totalEntries
        totalUniquePlayers
        totalRebuys
        totalAddons
        gameType
        gameVariant
        tournamentType
        gameTags
        venueId
        venueName
        doNotScrape
        existingGameId
      }
      saveResult {
        success
        gameId
        action
        message
      }
    }
  }
`;

// ===================================================================
// JOB PROGRESS SUBSCRIPTION (NEW in v2.0)
// ===================================================================

/**
 * Subscribe to job-level progress events during a batch job.
 * Events include aggregate stats, status changes, and timing info.
 * 
 * This subscription REPLACES polling-based monitoring and provides:
 * - Real-time status updates (RUNNING → COMPLETED, etc.)
 * - Live counters (processed, created, updated, errors)
 * - Duration tracking
 * - Error and stop reason information
 * 
 * @param jobId - The scraper job ID to subscribe to
 * 
 * @example
 * ```typescript
 * import { generateClient } from 'aws-amplify/api';
 * import { onJobProgress } from '../graphql/customSubscriptions';
 * 
 * const client = generateClient();
 * const subscription = client.graphql({
 *   query: onJobProgress,
 *   variables: { jobId: 'abc123' }
 * });
 * 
 * subscription.subscribe({
 *   next: ({ data }) => {
 *     const event = data.onJobProgress;
 *     console.log(`Progress: ${event.totalURLsProcessed} processed, status: ${event.status}`);
 *   },
 *   error: (err) => console.error('Subscription error:', err)
 * });
 * ```
 */
export const onJobProgress = /* GraphQL */ `
  subscription OnJobProgress($jobId: ID!) {
    onJobProgress(jobId: $jobId) {
      jobId
      entityId
      status
      stopReason
      totalURLsProcessed
      newGamesScraped
      gamesUpdated
      gamesSkipped
      errors
      blanks
      notFoundCount
      notPublishedCount
      currentId
      startId
      endId
      startTime
      durationSeconds
      successRate
      averageScrapingTime
      s3CacheHits
      consecutiveNotFound
      consecutiveErrors
      consecutiveBlanks
      lastErrorMessage
      publishedAt
    }
  }
`;

// ===================================================================
// MUTATIONS FOR LAMBDA TO PUBLISH EVENTS
// ===================================================================

/**
 * Mutation used by Lambda to publish game processing events.
 * This triggers the onGameProcessed subscription for all listeners.
 * 
 * USAGE (in Lambda):
 * @example
 * await client.graphql({
 *   query: publishGameProcessedMutation,
 *   variables: {
 *     jobId: job.jobId,
 *     event: {
 *       jobId: job.jobId,
 *       entityId: job.entityId,
 *       tournamentId: 12345,
 *       action: 'CREATED',
 *       // ... other fields
 *     }
 *   }
 * });
 */
export const publishGameProcessedMutation = /* GraphQL */ `
  mutation PublishGameProcessed($jobId: ID!, $event: GameProcessedEventInput!) {
    publishGameProcessed(jobId: $jobId, event: $event) {
      jobId
      tournamentId
      action
      processedAt
    }
  }
`;

/**
 * Mutation used by Lambda to publish job progress events.
 * This triggers the onJobProgress subscription for all listeners.
 * 
 * USAGE (in Lambda):
 * @example
 * await client.graphql({
 *   query: publishJobProgressMutation,
 *   variables: {
 *     jobId: job.jobId,
 *     event: {
 *       jobId: job.jobId,
 *       entityId: job.entityId,
 *       status: 'RUNNING',
 *       totalURLsProcessed: stats.processed,
 *       newGamesScraped: stats.created,
 *       gamesUpdated: stats.updated,
 *       gamesSkipped: stats.skipped,
 *       errors: stats.errors,
 *       blanks: stats.blanks,
 *       notFoundCount: stats.notFoundCount,
 *       notPublishedCount: stats.notPublishedCount,
 *       durationSeconds: Math.floor((Date.now() - startTime) / 1000),
 *       currentId: currentTournamentId,
 *       startId: job.startId,
 *       endId: job.endId,
 *     }
 *   }
 * });
 */
export const publishJobProgressMutation = /* GraphQL */ `
  mutation PublishJobProgress($jobId: ID!, $event: JobProgressEventInput!) {
    publishJobProgress(jobId: $jobId, event: $event) {
      jobId
      entityId
      status
      totalURLsProcessed
      newGamesScraped
      gamesUpdated
      gamesSkipped
      errors
      blanks
      notFoundCount
      notPublishedCount
      durationSeconds
      publishedAt
    }
  }
`;

// ===================================================================
// TYPE DEFINITIONS - GAME PROCESSED
// ===================================================================

/**
 * Variables for onGameProcessed subscription
 */
export interface OnGameProcessedSubscriptionVariables {
  jobId: string;
}

/**
 * Response type for onGameProcessed subscription
 */
export interface OnGameProcessedSubscription {
  onGameProcessed: {
    jobId: string;
    entityId: string;
    tournamentId: number;
    url?: string | null;
    action: 'CREATED' | 'UPDATED' | 'SKIPPED' | 'ERROR' | 'NOT_FOUND' | 'NOT_PUBLISHED';
    message?: string | null;
    errorMessage?: string | null;
    processedAt: string;
    durationMs?: number | null;
    dataSource?: string | null;
    s3Key?: string | null;
    gameData?: {
      name?: string | null;
      gameStatus?: string | null;
      registrationStatus?: string | null;
      gameStartDateTime?: string | null;
      gameEndDateTime?: string | null;
      buyIn?: number | null;
      rake?: number | null;
      guaranteeAmount?: number | null;
      prizepoolPaid?: number | null;
      totalEntries?: number | null;
      totalUniquePlayers?: number | null;
      totalRebuys?: number | null;
      totalAddons?: number | null;
      gameType?: string | null;
      gameVariant?: string | null;
      tournamentType?: string | null;
      gameTags?: string[] | null;
      venueId?: string | null;
      venueName?: string | null;
      doNotScrape?: boolean | null;
      existingGameId?: string | null;
    } | null;
    saveResult?: {
      success: boolean;
      gameId?: string | null;
      action?: string | null;
      message?: string | null;
    } | null;
  } | null;
}

// ===================================================================
// TYPE DEFINITIONS - JOB PROGRESS (NEW in v2.0, FIXED in v2.1)
// ===================================================================

/**
 * Variables for onJobProgress subscription
 */
export interface OnJobProgressSubscriptionVariables {
  jobId: string;
}

/**
 * Response type for onJobProgress subscription
 * 
 * FIXED v2.1: Added notFoundCount and notPublishedCount fields that were
 * present in the GraphQL query but missing from this interface.
 */
export interface OnJobProgressSubscription {
  onJobProgress: {
    jobId: string;
    entityId: string;
    status: string;
    stopReason?: string | null;
    totalURLsProcessed: number;
    newGamesScraped: number;
    gamesUpdated: number;
    gamesSkipped: number;
    errors: number;
    blanks: number;
    // FIXED v2.1: Added these fields that were missing
    notFoundCount?: number | null;      // Empty tournament slots (clearer name for blanks)
    notPublishedCount?: number | null;  // Real tournaments that are hidden/unpublished
    currentId?: number | null;
    startId?: number | null;
    endId?: number | null;
    startTime?: string | null;
    durationSeconds: number;
    successRate?: number | null;
    averageScrapingTime?: number | null;
    s3CacheHits?: number | null;
    consecutiveNotFound?: number | null;
    consecutiveErrors?: number | null;
    consecutiveBlanks?: number | null;
    lastErrorMessage?: string | null;
    publishedAt: string;
  } | null;
}

// ===================================================================
// JOB PROGRESS EVENT TYPE (for direct use)
// ===================================================================

/**
 * Type for job progress events (non-nullable version for use in callbacks)
 * 
 * FIXED v2.1: Added notFoundCount and notPublishedCount fields.
 */
export interface JobProgressEvent {
  jobId: string;
  entityId: string;
  status: string;
  stopReason?: string | null;
  totalURLsProcessed: number;
  newGamesScraped: number;
  gamesUpdated: number;
  gamesSkipped: number;
  errors: number;
  blanks: number;
  // FIXED v2.1: Added these fields
  notFoundCount?: number | null;
  notPublishedCount?: number | null;
  currentId?: number | null;
  startId?: number | null;
  endId?: number | null;
  startTime?: string | null;
  durationSeconds: number;
  successRate?: number | null;
  averageScrapingTime?: number | null;
  s3CacheHits?: number | null;
  consecutiveNotFound?: number | null;
  consecutiveErrors?: number | null;
  consecutiveBlanks?: number | null;
  lastErrorMessage?: string | null;
  publishedAt: string;
}

// ===================================================================
// SUBSCRIPTION HELPERS
// ===================================================================

/**
 * Helper to create a typed game processed subscription
 * This provides better type inference when using the subscription
 */
export const createGameProcessedSubscription = (jobId: string) => ({
  query: onGameProcessed,
  variables: { jobId } as OnGameProcessedSubscriptionVariables,
});

/**
 * Helper to create a typed job progress subscription
 * This provides better type inference when using the subscription
 */
export const createJobProgressSubscription = (jobId: string) => ({
  query: onJobProgress,
  variables: { jobId } as OnJobProgressSubscriptionVariables,
});

// ===================================================================
// RE-EXPORT TYPES FROM scraper.ts FOR CONVENIENCE
// ===================================================================

// These are re-exported so consumers can import everything from one place
export type {
  GameProcessedEvent,
  GameProcessedData,
  GameProcessedSaveResult,
  GameProcessedActionType,
  JobProgressStats,
} from '../types/scraper';