// src/hooks/useBulkGameFetcher.ts

import { useState, useCallback } from 'react';
import { fetchGameDataRangeFromBackend } from '../services/gameService';
import type { BulkGameSummary } from '../types/game';
import { GameStatus, RegistrationStatus } from '../API';

// ## Type Guards ##
// These functions check if a string from the backend is a valid enum member.
// This is necessary because the Lambda returns generic strings, but our frontend
// types expect the strict enums generated by Amplify.

/**
 * Checks if a given value is a valid member of the GameStatus enum.
 * @param value The value to check.
 * @returns True if the value is a valid GameStatus, otherwise false.
 */
const isValidGameStatus = (value: any): value is GameStatus => {
    // `Object.values` gets all possible enum values (e.g., "SCHEDULED", "RUNNING").
    // We then check if the input string is included in that array.
    return Object.values(GameStatus).includes(value);
};

/**
 * Checks if a given value is a valid member of the RegistrationStatus enum.
 * @param value The value to check.
 * @returns True if the value is a valid RegistrationStatus, otherwise false.
 */
const isValidRegistrationStatus = (value: any): value is RegistrationStatus => {
    return Object.values(RegistrationStatus).includes(value);
};


// ## The Hook ##
// This custom hook manages the state for fetching a range of game summaries.

export const useBulkGameFetcher = () => {
    const [summaries, setSummaries] = useState<BulkGameSummary[]>([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const fetchGames = useCallback(async (startId: number, endId: number) => {
        setLoading(true);
        setError(null);
        try {
            const results = await fetchGameDataRangeFromBackend(startId, endId);
            
            // Map the raw results from the backend to our strictly-typed `BulkGameSummary`.
            // This is where the type guards are used to prevent type errors.
            const typedSummaries: BulkGameSummary[] = results.map(res => ({
                id: res.id,
                name: res.name || null,
                // Use the type guard: if the backend string is a valid status, use it. Otherwise, undefined.
                gameStatus: isValidGameStatus(res.status) ? res.status : undefined,
                registrationStatus: isValidRegistrationStatus(res.registrationStatus) ? res.registrationStatus : undefined,
                gameStartDateTime: res.gameStartDateTime || null,
                inDatabase: res.inDatabase || false,
                doNotScrape: res.doNotScrape || false,
                error: res.error || null,
            }));

            setSummaries(typedSummaries);

        } catch (err: any) {
            console.error("Failed to fetch game range:", err);
            setError(err.message || 'An unknown error occurred.');
        } finally {
            setLoading(false);
        }
    }, []);

    return { summaries, loading, error, fetchGames };
};