import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

// Import Amplify and the Authenticator UI component
import { Amplify } from 'aws-amplify'
import { Authenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css' // Import default styles

// Import the configuration file generated by Amplify
import config from './aws-exports.js'

// Configure Amplify
Amplify.configure(config)

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    {/* Wrap your App component with the Authenticator */}
    <Authenticator>
      {({ signOut, user }) => (
        <main>
          <App />
          {/* You can optionally pass signOut and user props to App */}
        </main>
      )}
    </Authenticator>
  </React.StrictMode>,
)