// graphql/aiInsightsOperations.ts
// Custom AI Insights GraphQL Operations
// Note: Other queries/mutations are auto-generated by Amplify

export const listMetricsPacksByEntity = /* GraphQL */ `
  query ListMetricsPacksByEntity(
    $entityId: ID!
    $periodKey: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $limit: Int
    $nextToken: String
  ) {
    metricsPacksByEntity(
      entityId: $entityId
      periodKey: $periodKey
      sortDirection: $sortDirection
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        entityId
        reportType
        periodKey
        periodLabel
        generatedAt
        snapshotsIncluded
        gamesIncluded
        venuesIncluded
        dataCompleteness
      }
      nextToken
    }
  }
`;

export const listDirectorReportsByEntity = /* GraphQL */ `
  query ListDirectorReportsByEntity(
    $entityId: ID!
    $periodKey: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $limit: Int
    $nextToken: String
  ) {
    directorReportsByEntity(
      entityId: $entityId
      periodKey: $periodKey
      sortDirection: $sortDirection
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        entityId
        reportType
        periodKey
        metricsPackId
        reportData
        status
        generatedAt
        modelName
        totalCost
        reportVersion
      }
      nextToken
    }
  }
`;