// graphql/enrichmentOperations.ts
// ===================================================================
// ENRICHMENT & FINANCIALS GRAPHQL OPERATIONS
// ===================================================================
//
// This file provides GraphQL operations for the enrichment pipeline.
//
// IMPORTANT: Main operations are RE-EXPORTED from auto-generated files
// to avoid duplicate operation name errors during Amplify codegen.
// Custom operations use unique names (suffixed with "Custom" or "Lite").
//
// ===================================================================

// ===================================================================
// RE-EXPORT AUTO-GENERATED OPERATIONS
// ===================================================================
//
// These are auto-generated by Amplify codegen in mutations.ts and queries.ts.
// We re-export them with names that match what our services expect.
//
// The auto-generated operations have these names:
// - enrichGameData (mutation)
// - calculateGameFinancials (mutation)
// - previewGameFinancials (query)
// - previewEnrichment (query) - may not exist yet, see custom definition below

export { enrichGameData as enrichGameDataMutation } from './mutations';
export { calculateGameFinancials as calculateGameFinancialsMutation } from './mutations';
export { previewGameFinancials as previewGameFinancialsQuery } from './queries';

// NOTE: If previewEnrichment exists in your queries.ts, uncomment this line:
// export { previewEnrichment as previewEnrichmentQuery } from './queries';

// ===================================================================
// CUSTOM OPERATIONS (unique names to avoid conflicts)
// ===================================================================

/**
 * Preview enrichment without side effects
 * 
 * If previewEnrichment is auto-generated in queries.ts, you can import that instead.
 * This custom version uses a unique operation name to avoid conflicts.
 * 
 * Operation name: "PreviewEnrichmentCustom" (unique)
 */
export const previewEnrichmentQuery = /* GraphQL */ `
  query PreviewEnrichmentCustom($input: EnrichGameDataInput!) {
    previewEnrichment(input: $input) {
      success
      
      validation {
        isValid
        errors {
          field
          message
          code
        }
        warnings {
          field
          message
          code
        }
      }
      
      enrichedGame {
        tournamentId
        existingGameId
        name
        gameType
        gameVariant
        gameStatus
        registrationStatus
        gameStartDateTime
        gameEndDateTime
        buyIn
        rake
        venueFee
        hasGuarantee
        guaranteeAmount
        totalBuyInsCollected
        rakeRevenue
        prizepoolPlayerContributions
        prizepoolAddedValue
        prizepoolSurplus
        guaranteeOverlayCost
        gameProfit
        totalUniquePlayers
        totalEntries
        venueId
        venueAssignmentStatus
        venueAssignmentConfidence
        suggestedVenueName
        tournamentSeriesId
        seriesAssignmentStatus
        seriesAssignmentConfidence
        suggestedSeriesName
        isSeries
        seriesName
        recurringGameId
        recurringGameAssignmentStatus
        recurringGameAssignmentConfidence
      }
      
      enrichmentMetadata {
        seriesResolution {
          status
          confidence
          matchedSeriesId
          matchedSeriesName
          wasCreated
          matchReason
        }
        recurringResolution {
          status
          confidence
          matchedRecurringGameId
          matchedRecurringGameName
          matchReason
        }
        venueResolution {
          status
          venueId
          venueName
          venueFee
          confidence
        }
        queryKeysGenerated
        financialsCalculated
        fieldsCompleted
        processingTimeMs
      }
    }
  }
`;

/**
 * Lightweight enrichment preview (minimal fields for quick display)
 * 
 * Operation name: "EnrichGameDataLite" (unique)
 */
export const enrichmentPreviewLite = /* GraphQL */ `
  mutation EnrichGameDataLite($input: EnrichGameDataInput!) {
    enrichGameData(input: $input) {
      success
      
      validation {
        isValid
        errors {
          field
          message
        }
        warnings {
          field
          message
        }
      }
      
      enrichedGame {
        name
        gameStatus
        venueId
        venueAssignmentStatus
        tournamentSeriesId
        seriesAssignmentStatus
        recurringGameId
        recurringGameAssignmentStatus
        rakeRevenue
        gameProfit
      }
      
      enrichmentMetadata {
        seriesResolution {
          status
          matchedSeriesName
          wasCreated
        }
        recurringResolution {
          status
          matchedRecurringGameName
        }
        venueResolution {
          status
          venueName
        }
        financialsCalculated
        processingTimeMs
      }
    }
  }
`;

/**
 * Lightweight financial summary (minimal fields for quick display)
 * 
 * Operation name: "CalculateGameFinancialsLite" (unique)
 */
export const financialsSummaryLite = /* GraphQL */ `
  mutation CalculateGameFinancialsLite($input: CalculateGameFinancialsInput!) {
    calculateGameFinancials(input: $input) {
      success
      mode
      
      summary {
        totalRevenue
        totalCost
        netProfit
        profitMargin
        guaranteeMet
        guaranteeOverlayCost
      }
      
      processingTimeMs
      error
    }
  }
`;

/**
 * Full save with enrichment - single call for scraper flow
 * Combines enrichment + save in one operation (set saveToDatabase: true)
 * 
 * Operation name: "EnrichAndSaveGameFull" (unique)
 */
export const enrichAndSaveGameMutation = /* GraphQL */ `
  mutation EnrichAndSaveGameFull($input: EnrichGameDataInput!) {
    enrichGameData(input: $input) {
      success
      
      validation {
        isValid
        errors {
          field
          message
          code
        }
        warnings {
          field
          message
          code
        }
      }
      
      enrichedGame {
        tournamentId
        name
        gameStatus
        venueId
        tournamentSeriesId
        recurringGameId
        rakeRevenue
        gameProfit
      }
      
      enrichmentMetadata {
        seriesResolution {
          status
          matchedSeriesName
          wasCreated
        }
        recurringResolution {
          status
          matchedRecurringGameName
        }
        venueResolution {
          status
          venueName
        }
        processingTimeMs
      }
      
      saveResult {
        success
        gameId
        action
        message
        warnings
        playerProcessingQueued
        playerProcessingReason
        fieldsUpdated
      }
    }
  }
`;

// ===================================================================
// MIGRATION NOTES
// ===================================================================
//
// The following mutations have been REMOVED from the schema:
// - saveGame (was in saveGameFunction)
// - saveTournamentData (was in webScraperFunction)
//
// MIGRATION PATH:
// 
// OLD: saveGame(input: SaveGameInput!)
// NEW: enrichGameData(input: EnrichGameDataInput!) with options.saveToDatabase = true
//
// OLD: saveTournamentData(input: SaveTournamentInput!)  
// NEW: enrichGameData(input: EnrichGameDataInput!) with options.saveToDatabase = true
//
// The enrichGameData mutation:
// 1. Validates the data
// 2. Resolves venue, series, and recurring game relationships
// 3. Calculates financials
// 4. Saves to database (when saveToDatabase: true)
//
// See enrichmentService.ts for helper functions:
// - scrapedDataToEnrichInput() - converts ScrapedGameData to EnrichGameDataInput
// - saveGameDataToBackend() - drop-in replacement for gameService function
//
// ===================================================================
// OTHER FILES THAT NEED FIXING (duplicate operation names)
// ===================================================================
//
// 1. hooks/enrichment/useEnrichmentPreview.ts
//    - Has inline mutation "EnrichGameDataPreview" - rename to unique name
//    - Or import from this file instead
//
// 2. components/games/editor/GameEditorModal.tsx
//    - Has inline "saveGameMutation" referencing non-existent saveGame
//    - Replace with: import { saveGameDataToBackend } from 'services/enrichmentService'
//
// 3. graphql/entityOperations.ts
//    - Has "saveTournamentDataWithEntity" referencing non-existent saveTournamentData
//    - Delete this operation, use enrichmentService.saveGameDataToBackend() instead
//
// ===================================================================